import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const figures = path.join(root, 'figures');
const images = path.join(root, 'images');
const execFileAsync = promisify(execFile);
await mkdir(images, { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 670 }, deviceScaleFactor: 1.5 });
await page.goto(`file://${path.join(figures, 'bukatsu3_note-header.html')}`, { waitUntil: 'networkidle' });
await page.evaluate(() => document.fonts.ready);
await page.screenshot({ path: path.join('/tmp', 'bukatsu3_note-header-raw.png'), clip: { x: 0, y: 0, width: 1280, height: 670 } });
await execFileAsync('magick', [path.join('/tmp', 'bukatsu3_note-header-raw.png'), '-gravity', 'south', '-background', '#07111E', '-extent', '1920x1006', path.join(images, 'bukatsu3_note-header.png')]);
await page.screenshot({ path: path.join(images, 'bukatsu3_note-header-square.png'), clip: { x: 305, y: 0, width: 670, height: 670 } });
const preview = await browser.newPage({ viewport: { width: 300, height: 157 }, deviceScaleFactor: 1 });
await preview.goto(`file://${path.join(figures, 'bukatsu3_note-header.html')}`, { waitUntil: 'networkidle' });
await preview.evaluate(() => document.fonts.ready);
await preview.addStyleTag({ content: 'html,body{width:300px!important;height:157px!important}.canvas{transform:scale(.234375);transform-origin:top left}' });
await preview.screenshot({ path: path.join(images, 'bukatsu3_note-header-300px.png') });
const headerMobile = await browser.newPage({ viewport: { width: 375, height: 196 }, deviceScaleFactor: 1 });
await headerMobile.goto(`file://${path.join(figures, 'bukatsu3_note-header.html')}`, { waitUntil: 'networkidle' });
await headerMobile.evaluate(() => document.fonts.ready);
await headerMobile.addStyleTag({ content: 'html,body{width:375px!important;height:196px!important}.canvas{transform:scale(.29296875);transform-origin:top left}' });
await headerMobile.screenshot({ path: path.join(images, 'bukatsu3_note-header-375px.png') });
await page.close(); await preview.close(); await headerMobile.close();
const figure = await browser.newPage({ viewport: { width: 800, height: 940 }, deviceScaleFactor: 3 });
await figure.goto(`file://${path.join(figures, 'bukatsu3_fig1-cost.html')}`, { waitUntil: 'networkidle' });
await figure.evaluate(() => document.fonts.ready);
await figure.screenshot({ path: path.join(images, 'bukatsu3_fig1-cost.png'), clip: { x: 0, y: 0, width: 800, height: 940 } });
const figurePreview = await browser.newPage({ viewport: { width: 375, height: 441 }, deviceScaleFactor: 1 });
await figurePreview.goto(`file://${path.join(figures, 'bukatsu3_fig1-cost.html')}`, { waitUntil: 'networkidle' });
await figurePreview.evaluate(() => document.fonts.ready);
await figurePreview.addStyleTag({ content: 'html,body{width:375px!important;height:441px!important}.canvas{transform:scale(.46875);transform-origin:top left}' });
await figurePreview.screenshot({ path: path.join(images, 'bukatsu3_fig1-cost-375px.png') });
await figure.close(); await figurePreview.close();
const figure2 = await browser.newPage({ viewport: { width: 800, height: 1140 }, deviceScaleFactor: 3 });
await figure2.goto(`file://${path.join(figures, 'bukatsu3_fig2-cost-structure.html')}`, { waitUntil: 'networkidle' });
await figure2.evaluate(() => document.fonts.ready);
await figure2.screenshot({ path: path.join(images, 'bukatsu3_fig2-cost-structure.png'), clip: { x: 0, y: 0, width: 800, height: 1140 } });
const figure2Preview = await browser.newPage({ viewport: { width: 375, height: 534 }, deviceScaleFactor: 1 });
await figure2Preview.goto(`file://${path.join(figures, 'bukatsu3_fig2-cost-structure.html')}`, { waitUntil: 'networkidle' });
await figure2Preview.evaluate(() => document.fonts.ready);
await figure2Preview.addStyleTag({ content: 'html,body{width:375px!important;height:534px!important}.canvas{transform:scale(.46875);transform-origin:top left}' });
await figure2Preview.screenshot({ path: path.join(images, 'bukatsu3_fig2-cost-structure-375px.png') });
await figure2.close(); await figure2Preview.close();
const figure3 = await browser.newPage({ viewport: { width: 800, height: 940 }, deviceScaleFactor: 3 });
await figure3.goto(`file://${path.join(figures, 'bukatsu3_fig3-receiver.html')}`, { waitUntil: 'networkidle' });
await figure3.evaluate(() => document.fonts.ready);
await figure3.screenshot({ path: path.join(images, 'bukatsu3_fig3-receiver.png'), clip: { x: 0, y: 0, width: 800, height: 940 } });
const figure3Preview = await browser.newPage({ viewport: { width: 375, height: 441 }, deviceScaleFactor: 1 });
await figure3Preview.goto(`file://${path.join(figures, 'bukatsu3_fig3-receiver.html')}`, { waitUntil: 'networkidle' });
await figure3Preview.evaluate(() => document.fonts.ready);
await figure3Preview.addStyleTag({ content: 'html,body{width:375px!important;height:441px!important}.canvas{transform:scale(.46875);transform-origin:top left}' });
await figure3Preview.screenshot({ path: path.join(images, 'bukatsu3_fig3-receiver-375px.png') });
await figure3.close(); await figure3Preview.close(); await browser.close();
console.log('Rendered all note 3 images.');
