#!/usr/bin/env node

// マップの母数は代表例の安全性ではなく、投稿者自身の意見性で統一する。

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(
  root,
  "social-samples/henoko/henoko_hermes_arena_classified.json",
);
const outputPath = path.join(root, "docs/henoko-arena-data.js");
const pagePath = path.join(root, "docs/henoko-student-accident-reaction-map.html");

const issueIndex = {
  "政治的中立性": 0,
  "安全管理・事故原因": 1,
  "追悼・被害者の尊厳": 2,
  "平和教育の萎縮": 3,
  "政治利用・基地問題": 4,
  "報道・行政対応": 5,
};

function intensity(row) {
  const classification = row.classification || {};
  return {
    low: 0.28,
    medium: 0.62,
    high: 0.94,
  }[classification.intensity] ?? 0.45;
}

function stance(row) {
  const value = String(row.classification?.stance || "");
  if (value === "文科省判断を支持") return 1;
  if (value === "文科省判断に反発") return -1;
  return 0;
}

const rows = JSON.parse(await readFile(sourcePath, "utf8"));
const arenaRows = rows
  .filter((row) => row.classification?.is_opinion === true)
  .map((row) => ({
    i: issueIndex[row.classification.main_issue],
    e: intensity(row),
    x: stance(row),
    s: row.classification.summary || "投稿の要旨",
    u: row.url || "",
  }))
  .filter((row) => Number.isInteger(row.i));

const output =
  "/* Generated by scripts/build_henoko_arena.mjs. */\n" +
  "const HENOKO_ARENA_RAW=" +
  JSON.stringify(arenaRows) +
  ";\n";

await writeFile(outputPath, output);
const page = await readFile(pagePath, "utf8");
const inlineData =
  "/* HENOKO_ARENA_DATA_START */\nconst HENOKO_ARENA_RAW=" +
  JSON.stringify(arenaRows) +
  ";\n/* HENOKO_ARENA_DATA_END */";
const dataMarkerPattern =
  /\/\* HENOKO_ARENA_DATA_START \*\/[\s\S]*?\/\* HENOKO_ARENA_DATA_END \*\//;
if (!dataMarkerPattern.test(page)) {
  throw new Error("Henoko arena data markers were not found in the page");
}
const updatedPage = page.replace(
  dataMarkerPattern,
  inlineData,
);
await writeFile(pagePath, updatedPage);
console.log(`wrote ${arenaRows.length} arena points to ${outputPath}`);
